<?php

/**
 * @file
 * Contains day05.module.
 */

use Drupal\block\Entity\Block;
use GuzzleHttp\Exception\RequestException;

/**
 * Implements hook_cron().
 */
function day05_cron() {

  // Set up some variables.
  $endpoint = 'http://dev.markitondemand.com/MODApis/Api/v2/Quote/jsonp';

  // On cron run, cycle through all blocks.
  $blocks = Block::loadMultiple();

  foreach ($blocks as $block) {
    if (0 === strpos($block->id(), 'stock_exchange_rate_card') ) {

      $uuid = $block->getPlugin()->getDerivativeId();
      $block_content = \Drupal::service('entity.repository')
        ->loadEntityByUuid('block_content', $uuid);

      if ($block_content) {
        $block_symbol = $block_content->field_symbol->value;
        $uri = $endpoint . '?symbol=' . $block_symbol . '&callback=myFunction';

        try {
          $response = \Drupal::httpClient()->get($uri,
            ['headers' =>
              ['Accept' => 'text/plain']
            ]
          );

          $data = (string)$response->getBody();
          if (empty($data)) {
            return FALSE;
          }
          else {
            $json = substr($data, 11, -1);
            $data_decoded = json_decode($json);
            $block_content->set('field_last_price', $data_decoded->LastPrice);
            $block_content->set('field_change', $data_decoded->Change);
            $block_content->save();
          }
        }
        catch (RequestException $e) {
          return FALSE;
        }
      }
    }
  }
}
